const Assets = {
  _promo_banner: require('../assets/img/promo_banner.png'),
  _vegan_img: require('../assets/img/vegan_img.png'),
  _heathly_img: require('../assets/img/healthy_img.png'),
  _noodle_img: require('../assets/img/noddle.png'),
  _bg_main_img: require('../assets/img/bg-main.png'),
  _icon_search: require('../assets/img/icon_search.png'),
  _icon_filter: require('../assets/img/icon_filter.png'),
  _icon_notifiaction: require('../assets/img/Icon_Notifiaction.png'),
  _onboarding_bg: require('../assets/img/onboarding-bg.png'),
  _logo: require('../assets/img/Logo.png'),
  _img_onboarding_2: require('../assets/img/img-onboarding-2.png'),
  _img_onboarding_3: require('../assets/img/img-onboarding-3.png'),
  _icon_back: require('../assets/img/icon-back.png'),
  _forgot_sms_icon: require('../assets/img/forgot-sms-icon.png'),
  _dots: require('../assets/img/dots.png'),
  _forgot_email_icon: require('../assets/img/forgot-email-icon.png'),
  _eye_icon: require('../assets/img/eye-icon.png'),
  _succes_img: require('../assets/img/success-img.png'),
  _user_icon: require('../assets/img/user-icon.png'),
  _mail_icon: require('../assets/img/mail-icon.png'),
  _password_icon: require('../assets/img/password-icon.png'),
  _check_icon: require('../assets/img/check-icon.png'),
  _fb_icon: require('../assets/img/fb-icon.png'),
  _google_icon: require('../assets/img/google-icon.png'),
  _gallery_icon: require('../assets/img/gallery-icon.png'),
  _camera_icon: require('../assets/img/camera-icon.png'),
  _image_preview: require('../assets/img/image-preview.png'),
  _paypal: require('../assets/img/paypal.png'),
  _visa: require('../assets/img/visa.png'),
  _payonner: require('../assets/img/payoneer.png'),
  _location_icon: require('../assets/img/location-icon.png'),
  _ava_1: require('../assets/img/ava-1.png'),
  _ava_2: require('../assets/img/ava-2.png'),
  _ava_3: require('../assets/img/ava-3.png'),
  _profile_bg: require('../assets/img/profile-bg.png'),
  _profile_voucher_icon: require('../assets/img/voucher-icon.png'),
  _profile_edit_btn: require('../assets/img/edit-profile-btn.png'),
  _dish_1: require('../assets/img/dish.png'),
  _plus_icon: require('../assets/img/plus-icon.png'),
  _minus_icon: require('../assets/img/minus-icon.png'),
};

export default Assets;
